# Generated by Django 4.0.6 on 2022-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_category_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('KIN', 'KING'), ('NAC', 'NON-AC'), ('YAC', 'AC'), ('DEL', 'DELUXE')], max_length=3),
        ),
    ]
